zetodo/zeapp/urls.py
from .views import index, delete_task, task_detail

from django.urls import path

urlpatterns = [
    path('',view=index,name='index'),
    path('delete/<uuid:task_id>', view=delete_task, name='delete_task'),
    path('task_detail/<uuid:task_id>', view=task_detail, name='task_detail')
]

zetodo/zetodo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('zeapp.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG :
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

zetodo/zeapp/models.py
import uuid
from django.db import models
from django.utils.translation import gettext_lazy as _



class TaskModel(models.Model):
    PRIORITIES = [
        (0, "Faible"),
        (1, "Moyen"),
        (2, "Elevé"),
        (3, "Critique"),
    ]
    STATUS =  [
        (0, "A faire"),
        (1, "En cours"),
        (2, "Terminé"),
        (3, "Annulé"),
        (4, "En attente"),
        (5, "En pause"),
        (6, "En attente de validation")
        ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(_("Title"),max_length=100)
    memo = models.TextField(_("Description"),null=True,blank=True)
    priority = models.IntegerField(_("Priority"), choices=PRIORITIES,null=True,blank=True)
    duedate = models.DateField(_("Due date"),null=True,blank=True)
    status = models.IntegerField(_("Status"), choices=STATUS,null=True,blank=True)
    created_date = models.DateTimeField(_("Created date"), editable=False, auto_now_add=True)

    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ["-priority"]
        verbose_name = _("Task")
        verbose_name_plural = _("Tasks") 

zetodo/zeapp/forms.py
from django.forms import ModelForm, DateInput

from .models import TaskModel

class TaskDateInput(DateInput):
    input_type = "date"
    

class TaskModelForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class']='form-control'
        
    class Meta:
        model = TaskModel
        fields = ["title","memo","priority","duedate","status"]
        widgets = {
            "duedate": TaskDateInput(format="dd/mm/yyyy"),
        }

zetodo/zeapp/views.py
from typing import Dict
from uuid import UUID

from django.shortcuts import render
from django.http import HttpRequest, HttpResponse
from django.shortcuts import get_object_or_404, redirect
from django.contrib import messages

from .forms import TaskModelForm
from .models import TaskModel


def index(request: HttpRequest) -> HttpResponse:

    title = "ZeTodoApp"
    ctx : Dict = {
        'page_title': title
        }
    if(request.method == 'POST'):
        form = TaskModelForm(request.POST)
        if(form.is_valid()):
            form.save()
        else:
            messages.error(request, form.errors)
    tasks = TaskModel.objects.all()
    ctx['tasks'] = tasks
    
    return(render(request=request,context=ctx,template_name='zeapp/index.html'))

def delete_task(request: HttpRequest, task_id: UUID) -> HttpResponse:

    task = get_object_or_404(TaskModel, pk=task_id)
    task.delete()

    return(redirect('index', permanent=True))

def update_task(request: HttpRequest, task_id: UUID) -> HttpResponse:
    pass

def task_detail(request: HttpRequest, task_id: UUID) -> HttpResponse:
    
    task = get_object_or_404(TaskModel, pk=task_id)
    
    if request.method == "POST":
        if request.POST['title']:
            task.title = request.POST['title']
        if request.POST['memo']:
            task.memo = request.POST['memo']
        if request.POST['priority']:
            task.priority = request.POST['priority']
        if request.POST['status']:
            task.status = request.POST['status']
        if request.POST['duedate']:
            task.duedate = request.POST['duedate']
        task.save()
        return(redirect('index', permanent=True))
        
    form = TaskModelForm(instance=task)

    ctx : Dict = {
        'page_title' : 'Task detail-'+str(task.id),
        'task' : task,
        'form' : form,
    }

    return(render(request=request, context=ctx, template_name='zeapp/index.html'))

zetodo/zeapp/templates/zeapp/base.html
<!DOCTYPE html>
<html lang="en roboto-regular test">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {{ page_title}}
    </title>
    {% load static %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href=' {% static "zeapp/css/style.css" %} '>
    <!-- Include Bootstrap Datepicker plugin -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css">
</head>
<body class="page-top ">
    <div class="container">   

    {% block content %}
            
    {% endblock content %}
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>
    <script src="https://kit.fontawesome.com/d4503f3bff.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
</body>
</html>

zetodo/zeapp/templates/zeapp/components/app-logo.html
{% load static %}
<img class="card-img-top" src="{% static 'zeapp/image/png/1x/logo.png' %}" alt="" srcset="" >

zetodo/zeapp/templates/zeapp/components/new_task.html
<form action="" method="post">
    {% csrf_token %}
    <div class="input-group mb-3">
        <input name='title' id="title" type="text" class="form-control" aria-label="" aria-describedby="For typing new Task to Add" placeholder="Une tâche, une estime de sois ..." required>
        <div class="input-group-append">
            <button class="btn btn-success" type="submit"><i class="fa-solid fa-circle-plus"></i></button>
        </div>
      </div>
</form>

zetodo/zeapp/templates/zeapp/components/task_detail.html
<form class="task_detail" action="" method="post">
    {% csrf_token %}
    <div class="form-group">
        <label class=" font-weight-light text-secondary" for="task_title">Votre tâche en une phrase.</label>
        {{form.title}}
    </div>
    <div class="form-group">
        <label class="text-secondary font-weight-light" for="task_memo">Et si on décrivait votre tâche en 500 Caractère.</label>
        {{form.memo}}
        <!-- <textarea class="form-control" id="task_memo"  minlength="0" maxlength="500" placeholder="C'est toujours mieux de décrire en quoi consiste la tâche à faire....">     -->
        </textarea>
    </div>
    <div class="form-row">
        <div class="form-group col">
            <label for="id_priority" class="text-secondary font-weight-light" >Priorité</label>
            {{form.priority}}
        </div> 
        <div class="form-group col">
            <label for="id_status" class="text-secondary font-weight-light">Status</label>
            {{form.status}}
        </div>
        <div class="form-group col">
            <label for="id_duedate" class="text-secondary font-weight-light">Date de fin</label>
            {{form.duedate}}
            <!-- Create an input element with the datepicker class -->
            <!-- <input type="text" class="form-control datepicker" placeholder="Select a date"> -->


</script>
        </div>

    </div>
    <div class="inline-form">
        <button class="btn btn-success mr-auto" type="submit">Valider <i class="fa-regular fa-circle-check"></i></button>
        <a class="btn btn-outline-warning" href="{% url 'index' %}" role="button">Annuler <i class="fa-solid fa-ban" style="color: #FFD43B;"></i></a>
        <a class="btn btn-outline-danger" href="{% url 'delete_task' task.id %}" role="button">Supprimer <i class="fa-solid fa-trash-can" ></i></a>
    </div>
    
</form>

zetodo/zeapp/templates/zeapp/components/tasklist.html
<div id="taskList">
    <ul class="list-group" >
        {% for task in tasks %}
            <li class="list-group-item d-flex">
                <div class="mr-auto">
                    <span class="text-truncate font-weight-light pr-2">{{task.title | capfirst}}</span>  
                    <!-- <small class="text-muted font-italic">{{task.priority}} <strong>{{task.status}}</strong> {{task.duedate}}</small> -->
                </div>
                <span class="d-inline-block d-flex badge p-0 border-left" style="background-color: rgb(14, 14, 14);">
                    <a class="btn " href="{% url 'task_detail' task.id %}" role="button"><i class="fa-solid fa-pen-to-square " style="color: #077272;"></i></a>  
                    <a class="btn " href="{% url 'delete_task' task.id %}" role="button"><i class="fa-solid fa-trash-can" style="color: #b50303;"></i></a>
                </span>
            </li>
        {% endfor %}
    </ul>
</div>

zetodo/zeapp/templates/zeapp/index.html
{% extends "zeapp/base.html" %}
{% block content %}
    <section class="container">

        <div class="row justify-content-md-center my-4">
            <div class="col-md-7">
                <div class="card" style="background-color:rgba(24, 25, 32, 1)">
                    {% load static %}
                    <img class="card-img-top" src="{% static 'zeapp/image/png/1x/logo.png' %}" alt="" srcset="" >
                  <div class="card-body">
                    {% if messages %}
                        <ul class="messages">
                            {% for message in messages %}
                            <li{% if message.tags %} class="badge badge-danger"{% endif %}>{{ message }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                    {% if task %}
                        {% include "zeapp/components/task_detail.html" %}
                     {% else %}
                            {% include "zeapp/components/new_task.html" %}
                            {% if tasks %}
                                {% include "zeapp/components/tasklist.html" %}
                            {% else %}
                                <small class="font-italic text-muted ">Ajoutez une nouvelle tâche pour commencer.</small>
                            {% endif %}
                    {% endif %}
                    
                  </div>
                </div>
            </div>
        </div>
    </section>
    {% load static %}
    <script src="{% static 'zeapp/js/main.js' %}"></script>
{% endblock content %}